# 1. Stacking de Arreglos


In [4]:
import numpy as np

## Ejercicio 1:
1. Crea dos arrays 1D:
- a con los números del 1 al 3.
- b con los números del 4 al 6.

2. Une ambos arrays usando np.column_stack().
3. Imprime el resultado.


In [39]:
# Crea dos arrays 1D:
a = np.arange(1, 3)
b = np. arange(4, 6)
print(a)
print(b)

[1 2]
[4 5]


In [42]:
# Une ambos arrays usando np.column_stack().
stacked = np.column_stack((a,b))

In [43]:
print("Resultado de np.column_stack((a, b)):")
print(stacked)

Resultado de np.column_stack((a, b)):
[[1 4]
 [2 5]]


Imagina que trabajas en un entorno de retail B2B donde necesitas analizar datos mensuales de tus clientes. Por ejemplo, supongamos que tienes dos conjuntos de datos:

- **Ventas mensuales:** La cantidad de unidades vendidas de un producto en cada mes.
- **Inventario inicial mensual:** La cantidad de unidades disponibles al inicio de cada mes en el almacén del cliente.

Queremos combinar estos datos para poder, por ejemplo, analizar la relación entre las ventas y el inventario disponible, lo que puede ayudar a entender la rotación de stock o prever futuras necesidades de reposición.

A continuación, un ejemplo real usando `np.column_stack()`:

---


In [44]:
import numpy as np

ventas = np.array([120, 150, 170, 160, 180, 200])

inventario =  np.array([500, 480, 460, 450, 430, 410])


# Utilizamos np.column_stack() para combinar ambos arrays.
# Cada fila de 'datos' corresponderá a un mes, con la primera columna siendo ventas
# y la segunda columna el inventario disponible.

datos = np.column_stack((ventas, inventario))

print("Datos combinados (ventas, inventario):")
print(datos)

Datos combinados (ventas, inventario):
[[120 500]
 [150 480]
 [170 460]
 [160 450]
 [180 430]
 [200 410]]


`

---

### Explicación del ejemplo

1. **Datos separados:**  
   - El array `ventas` contiene el número de unidades vendidas en cada mes.  
   - El array `inventario` contiene el inventario disponible al inicio de cada mes.

2. **Uso de `np.column_stack()`:**  
   - Al aplicar `np.column_stack((ventas, inventario))`, se crea una nueva matriz 2D.  
   - Cada fila de esta matriz corresponde a un mes, donde:
     - La **primera columna** representa las ventas.
     - La **segunda columna** representa el inventario.

3. **Ventajas para el análisis:**  
   - Esta estructura te permite realizar análisis estadísticos o aplicar modelos predictivos.  
   - Por ejemplo, podrías usar regresión para ver cómo el inventario afecta las ventas, o identificar patrones en la relación entre ambos.

En un entorno de retail B2B, combinar datos de esta manera es muy útil para integrar múltiples indicadores y obtener una visión más completa del desempeño de tus clientes o de tus productos. ¡Así puedes tomar decisiones más informadas!

# 2. Transposición y Cambio de Forma (Reshaping)

Concepto:
- Reshape: Cambia la forma de un array sin cambiar sus datos.

- Transposición: Cambia las filas por columnas, lo que es útil para matrices.


## Ejercicio 2:
- Crea un array 1D con los números del 0 al 5 usando np.arange().
- Transforma ese array en una matriz de 3 filas y 2 columnas usando .reshape(3,2).
- Obtén la transpuesta de esta matriz usando .T.
- Imprime tanto la matriz original como su transpuesta.


In [50]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [51]:
# Transforma ese array en una matriz de 3 filas y 2 columnas usando .reshape(3,2).

b = x.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [53]:
# Paso 3: Transponer la matriz
b_transpuesta = b.T
print(b_transpuesta)

[[0 3]
 [1 4]
 [2 5]]


In [56]:
b_transpuesta_denuevo = b_transpuesta.T

In [57]:
b_transpuesta_denuevo

array([[0, 1, 2],
       [3, 4, 5]])

# 3. Creación de Matrices Diagonales

Concepto:
- np.diag() puede utilizarse de dos maneras:

- Si le pasas una lista (o array 1D), crea una matriz diagonal con esos elementos en la diagonal principal.
- Si le pasas una matriz, extrae la diagonal.


## Ejercicio 3:
- Crea un array 1D con los números [1, 2, 3].
- Usa np.diag() para crear una matriz diagonal a partir de ese array.
- Imprime el resultado.

In [67]:
# - Crea un array 1D con los números [1, 2, 3].
a = np.arange(1,4)

In [72]:
print(a)

[1 2 3]


In [74]:
# - Usa np.diag() para crear una matriz diagonal a partir de ese array.
diag = np.diag(a)
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Ejercicio Integrador: Combinando Conceptos




### **Objetivo:**
Crea una función que realice lo siguiente:
1. Reciba dos arrays 1D y los apile columna a columna.
2. Cambie la forma del array apilado a otra dimensión (por ejemplo, 3 filas y 2 columnas, si es posible).
3. Devuelva tanto el array original apilado como su transpuesta.

### **Pista:**
- Asegúrate de que la cantidad total de elementos sea la adecuada para el reshape.
- Puedes utilizar la función `np.prod()` para comprobar el número total de elementos.


In [84]:
def procesa_arrays(a, b):
    #Reciba dos arrays 1D y los apile columna a columna.
    apilado = np.column_stack((a,b))
    print("Array apilado")
    print(apilado)
    # Cambie la forma del array apilado a otra dimensión (por ejemplo, 3 filas y 2 columnas, si es posible).
    total_elementos = apilado.size
    print(f"los elementos son {total_elementos}")
    # Para este ejercicio, vamos a intentar cambiar la forma a (3, ?)
    # Buscamos un divisor de total_elementos igual a 3
    if total_elementos % 3 == 0:
        nuevo_numero_columnas = total_elementos // 3
        reshaped = apilado.reshape(3, nuevo_numero_columnas)
        print(f"\nArray con nueva forma (3, {nuevo_numero_columnas}):")
        print(reshaped)
        print("\nTranspuesta del array reestructurado:")
        print(reshaped.T)
    else:
        print("\nNo es posible reestructurar el array a 3 filas sin modificar el total de elementos.")

        
        
        

    

In [85]:
a = np.arange(1, 4)
b = np.arange(4, 7)

procesa_arrays(a, b)

Array apilado
[[1 4]
 [2 5]
 [3 6]]
los elementos son 6

Array con nueva forma (3, 2):
[[1 4]
 [2 5]
 [3 6]]

Transpuesta del array reestructurado:
[[1 2 3]
 [4 5 6]]
